// Fiver - regenerate src/data/words.ts from a SCOWL distribution.
//
// The word pools are committed, so this is not part of the build. It exists so
// the derivation is reproducible and reviewable rather than an opaque blob.
//
//   1. Download and unpack SCOWL from http://wordlist.aspell.net/
//   2. node scripts/build-words.mjs <path-to>/scowl-<version>/final
//
// SCOWL grades words into frequency buckets. Buckets 10-35 are words an
// ordinary reader knows, which is what an answer has to be; every bucket is
// fair game as a *guess*, because rejecting a real word the player typed is
// the most irritating thing this kind of game can do.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const WORD_LENGTH = 5;
const ANSWER_BUCKETS = ["10", "20", "35"];

const finalDir = process.argv[2];
if (!finalDir) {
  console.error("usage: node scripts/build-words.mjs <scowl>/final");
  process.exit(1);
}

/** SCOWL files are latin-1 and one word per line. */
function readWords(file) {
  return readFileSync(join(finalDir, file), "latin1").split(/\s+/).filter(Boolean);
}

const files = readdirSync(finalDir).filter((f) => f.startsWith("english-words."));
if (files.length === 0) {
  console.error(`no english-words.* files in ${finalDir}`);
  process.exit(1);
}

/** Lower-case, unaccented, alphabetic only - no proper nouns, no apostrophes. */
const isPlain = (w) => /^[a-z]+$/.test(w);

const everyWord = new Set();
const guesses = new Set();
const answerCandidates = new Set();

for (const file of files) {
  const bucket = file.slice("english-words.".length);
  for (const word of readWords(file)) {
    if (!isPlain(word)) continue;
    everyWord.add(word);
    if (word.length !== WORD_LENGTH) continue;
    guesses.add(word);
    if (ANSWER_BUCKETS.includes(bucket)) answerCandidates.add(word);
  }
}

/**
 * A trailing S is only boring when it is an inflection.
 *
 * Testing the stem rather than the last letter is what keeps `atlas`, `chess`,
 * `bliss` and `bonus` as answers while dropping `aches` and `films`. Dropped
 * words remain perfectly valid guesses.
 */
function isInflection(word) {
  if (!word.endsWith("s")) return false;
  if (everyWord.has(word.slice(0, -1))) return true;
  return word.endsWith("es") && everyWord.has(word.slice(0, -2));
}

const answers = [...answerCandidates].filter((w) => !isInflection(w)).sort();
const allGuesses = [...guesses].sort();

const header = `// GENERATED by scripts/build-words.mjs - do not edit by hand.
//
// Source: SCOWL ${process.env.SCOWL_VERSION ?? "2020.12.07"} by Kevin Atkinson,
// http://wordlist.aspell.net/ - see SCOWL-COPYRIGHT.txt beside this file. The
// notice must travel with the data.
//
// ANSWERS are SCOWL frequency buckets ${ANSWER_BUCKETS.join("/")} (words an ordinary reader
// knows) with inflected plurals removed. GUESSES is every ${WORD_LENGTH}-letter word SCOWL
// knows, so a real word is never rejected. Every answer is also a guess.
`;

const body = `
/** Words the game may choose. ${answers.length} of them. */
export const ANSWERS: readonly string[] = ${JSON.stringify(answers)};

/** Words the game will accept as a guess. ${allGuesses.length} of them. */
export const GUESSES: readonly string[] = ${JSON.stringify(allGuesses)};
`;

writeFileSync(new URL("../src/data/words.ts", import.meta.url), header + body, "utf8");
console.log(`answers ${answers.length}, guesses ${allGuesses.length}`);
